boostorg/filesystem

- src/path.cpp
See https://svn.boost.org/trac/boost/ticket/4688
We do the same as on Mac OS X and assume the filesystem uses utf-8.
Signed-off-by: Jessica Hamilton <jessica.l.hamilton@gmail.com>
> haiku: don't crash because of unsupported locale in libstdc++

- src/unique_path.cpp
If two threads call unique_path at the same time for the first time in the program run,
both initial calls to CryptAcquireContext can fail. Both threads will then call the function
with CRYPT_NEWKEYSET, but only one of these threads can succeed. The other will
fail with NTE_EXISTS.
This patch makes it so that if a call fails with that error, it will try to call without the
flag one more time, in case another thread created the key set in the meantime.
This also applies the patch from trac report #7506. Using these additional flags
is the right thing to do.
> Fix a race condition in unique_path.

- include/boost/filesystem/operations.hpp
The comment in boost/iterator.hpp mentions that the file is obsolete and will be deprecated, and it is not used anyway.
Tested with MSVC 14.
> Remove unused deprecated include

- include/boost/filesystem/path.hpp
- test/path_test.cpp
- test/path_unit_test.cpp
When using Boost.Filesystem from a project compiled as C++/CX code,
compilation fails with a syntax error, because generic is a keyword.
error C2059: syntax error: 'generic'
See section "Generic interfaces" in C++/CX here: https://msdn.microsoft.com/en-us/library/hh755792.aspx
> Rename generic() to generic_path(), since generic is a keyword in C++/CX

- doc/reference.html
`stem()` and `extension()` member functions doesn't have parameter.
> fix signature stem(), extension() member functions

- src/operations.cpp
The space(p, ec) implementation assigned a wrong
error value to the given error_code object.
Instead of getting the error value from errno,
the code used the value '-1!=0'.
Signed-off-by: Christoph Müllner <christophm30@gmail.com>
> Fix errno propagation in space(p, ec).

- src/operations.cpp
This pull requests cleans up `_FILE_OFFSET_BITS` #if-ery in `operations.cpp`, fixes compilation with new Android NDKs for old Android APIs (issue #65) and, thanks to @Lastique's patch, provides better error checking in `resize_file()` function.
Differences from other pull requests, like #52 and #67:
* Instead of taking easy approach like
```c++
#if !MY_SETUP
// I don't care about the mess here.
#endif 
```
, which may eventually lead to #if-ery like
```c++
#if !SETUP_3
#if !SETUP_2
#if !SETUP_1
...
#else
...
#endif
#endif 
#endif 
```
, I am making attempt to clean the mess and provide "flat" #if-ery like
```c++
#if SETUP_1
...
#elif SETUP_2
...
#else
...
#endif
```
* During the cleanup, it turns out the either `_FILE_OFFSET_BITS`, or `__USE_FILE_OFFSET64`, or both (!) is always defined, …
> Fix compilation for Android and clean up _FILE_OFFSET_BITS #if-ery

- src/operations.cpp
In our case (we haven't gotten to the bottom of exactly why), `sysconf()` returns -1 and sets `errno == 38` (ENOSYS). When iterating over a directory, this lead to that error incorrectly being propagated after incrementing past the last directory entry.
> Reset 'errno' after 'sysconf()'

- src/operations.cpp
Call the detail versions, which take pointers, rather than converting the pointers to references and back (which is UB).
> Fix undefined behavior in detail::copy

- src/operations.cpp
The directory_iterator(const path& p) constructor calls
detail::directory_iterator_construct passing nullptr (as 0) for the ec
parameter.
detail::directory_iterator_construct may call
directory_iterator::increment(*ec) which dereferences the nullptr provoking
undefined behaviour.
On GCC, and probably many other compilers, it seems that this merely causes
a null reference to be passed to directory_iterator::increment which in
turn, turns it back into nullptr when calling
detail::directory_iterator_increment which knows how to deal with the
nullptr and is happy.
Unfortunately, directory_iterator::increment(system::error_code& ec) is
marked noexcept (unlike the version that takes no arguments) but
detail::directory_iterator_increment throws exceptions when ec == nullptr.
This results in …
> directory_iterator_construct: Avoid provoking undefined behaviour

- src/operations.cpp
Remove an #if from operations.cpp that used to be necessary for the file to compile with PGI C++, but causes compilation errors with PGI C++ compilers of the last few years.
> Update PGI C++ compiler support

- src/operations.cpp
`readdir_r` has been deprecated and has problems of its own[1]. glibc 2.24 marked
`readdir_r` as deprecated and may eventually remove it. At the same time, plain
`readdir` is thread-safe if different threads call it for different directory
streams, which is fine in our case.
[1]: http://man7.org/linux/man-pages/man3/readdir_r.3.html
> Don't use readdir_r on Linux and Android

- doc/deprecated.html
- doc/design.htm
- doc/faq.htm
- doc/reference.html
- doc/tickets.html
- doc/tutorial.html
- doc/v3_design.html
Found using [mwic](http://jwilk.net/software/mwic) and [anorack](https://github.com/jwilk/anorack).
> Fix typos in documentation

- test/operations_test.cpp
The `GetUserDefaultUILanguage` is available for a quite long time already (about 19 years for Cygwin, and 7-12 years for MinGW).
Fixes test fails on non-EN system locales. More info on the symmetrical PR for System https://github.com/boostorg/system/pull/40
> operations_test: Enable locale query on MinGW/Cygwin

- include/boost/filesystem/path.hpp
- src/operations.cpp
WinCE has no current directory. So reject attempts to change it and treat the root as the current directory.
> WinCE has no current directory

- include/boost/filesystem/path.hpp
<boost/io/detail/quoted_manip.hpp> is now just a deprecated forwarding header for backward compatibility, and will be removed eventually.
> Include the public quoted header from IO

- src/operations.cpp
- test/operations_test.cpp
#100 became big and mixed unrelated things. So here is just the part making the symlink functions available if the runtime supports it. This is done by checking whether the functions exist (as before) and the compile time checks are not required. Only issue seen is `SYMBOLIC_LINK_FLAG_DIRECTORY` being not defined on low API levels, but as other implementations do: Just define it to the documented value for those rare cases (e.g. Cygwin using a pre XP default API level)
> Remove API level checks in symlink functions in favor of runtime checks

- src/operations.cpp
- test/Jamfile.v2
- test/issues/99_canonical_with_junction_point.cpp
Resolving junction points in read_symlink and canonical is wrong making it unusable: It silently returns the wrong results.
Issues identified:
- read_symlink does not handle junction points and reads the wrong struct
- canonical tries to resolve the root_name as a symlink. On windows this could be `C:` and refers to the current working directory on C. Hence depending if the current dir is a symlink canonical resolves the root_name to the current dir which is wrong
Supersedes #45
> Fix canonical and read_symlink for junction points

- src/operations.cpp
- test/Jamfile.v2
- test/issues/reparce_tag_file_placeholder.cpp
Correct handling of placeholder file (https://msdn.microsoft.com/en-us/windows/compatibility/placeholder-files) in status. If 'is_reparse_point_a_symlink' returns false, return reparse_file as status. Otherwise resolve target and retake attributes of it.
> Correct handling status of reparse point

- src/directory.cpp
- src/operations.cpp
[WASI](https://wasi.dev/) is a POSIX-like platform that has a few important differences:
* There is no concept of a mutable current directory. However, WASI host environment can provide a directory called `.` in the filesystem namespace that fulfills a similar role.
* There is no concept of a file mode, and no `chmod` call.
* There is no concept of a filesystem, and no `statfs` call.
* There is no `readdir_r` call because there are no threads.
> Add WASI platform support

- include/boost/filesystem/directory.hpp
- test/operations_test.cpp
This fixes a problem that is_symlink(directory_entry) always returns
false, even if directory_entry is indeed a symlink. This change makes
is_symlink(directory_entry) behave the same as is_symlink(path) and
use symlink_status().
> is_symlink(directory_entry) should use symlink_status().

- doc/reference.html
The opening tag was placed between the letter i and s in is_directory instead of before the i.
This PR fixes that small mistake.
> Fix misplaced link opening tag for is_directory

- .github/workflows/ci.yml
- test/issues/reparse_tag_file_placeholder.cpp
Add jobs using MSYS2 MinGW to GHA
Config copied from boost-ci
This is the configuration where I see #321 although it seems to be only triggered by `-Wextra` not `-Wall`: https://godbolt.org/z/3fqjG7zM3
> Add CI jobs for MinGW32/64

- build.jam
- build/Jamfile.v2
- config/Jamfile.v2
- test/Jamfile.v2
- test/deprecated_test.cpp
This is part of the effort to make the Boost libraries "modular" for build and consumption. See https://lists.boost.org/Archives/boost/2024/01/255704.php and https://github.com/grafikrobot/boost-b2-modular/blob/b2-modular/README.adoc for more information.
This PR depends on the following other PRs being merged to both develop and master branches of the respective repos:
- https://github.com/boostorg/boost/pull/854
This PR will be changed to ready for review, i.e. not draft, when the above are merged. Do not merge this one until that time.
> Add support for modular build structure.
